version: "3.8"

services:
  nextjs:
    image: node
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/app
