# Étape 1 : Utiliser une image Node.js 20 LTS comme image de base
FROM node:20-alpine

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers `package.json` et `package-lock.json`
COPY package*.json ./

# Étape 4 : Installer les dépendances du projet
RUN npm install

# Étape 5 : Copier le reste du code de l'application
COPY . .

# Étape 6 : Construire l'application Next.js
RUN npm run build

# Étape 7 : Exposer le port 3000 pour le conteneur
EXPOSE 3000

# Étape 8 : Démarrer l'application
CMD ["npm", "run", "start"]
